# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# name: Advanced Usage

# on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args:  ${{ env.workspace }}/README.md --pdf-engine=xelatex -o resume_master_v1.pdf
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output

# jobs:
#   generate_pdf:
#     runs-on: ubuntu-latest
#     steps:
#       - name: My first step
#         uses: docker://pandoc/latex:2.6
#       - run: pandoc README.md --pdf-engine=xelatex -o resume_master_v1.pdf
#   convert_via_pandoc:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#       - run: echo "foo" > input.txt  # create an example file
#       - uses: docker://pandoc/core:2.9
#         with:
#           args: README.md --pdf-engine=xelatex -o resume_master_v1.pdf
#   my_first_job:
#     steps:
#       - name: My first step
#         uses: docker://gcr.io/cloud-builders/gradle
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
#     - name: My first step
#       uses: docker://gcr.io/cloud-builders/gradle
#     # convert md file into pdf
# #     - uses: actions/checkout@master
# #     - uses: r-lib/actions/setup-pandoc@v1
# #       with:
# #         pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.
#     #- run: cat resume.md | pandoc -t latex -o master_resume_v1.pdf
# #     - run: pandoc resume_master_raw.md --pdf-engine=xelatex -o master_resume_v1.pdf


